### ISSUE TITLE
Drill Hardware GATHER_SLOW

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#10]
The GATHER_SLOW option as described in the Wiki is not yet implemented. Additionnaly, I'm not sure how to make the digging animation last 4 ticks without modifying too much the client-side code. If it becomes too much trouble, I'll just get rid of it.

As of right now, Both the GATHER_SLOW and GATHER_FAST option yields the same result (1 tick).

**Comment by meet-mrmaker** [comment]
What about using a simple gather and complex gather, instead of altering the amount of ticks, it could be used to make resource gathering more efficient. i.e. If I used simple, i'd yield 1 Iron/Copper, if I used complex i'd yield 2,3 or 4 Iron/Copper but with a higher energy cost.

**Comment by simon987** [comment]
Problem is that there is only space for 1 item right now. To be honest I think that it would be best to remove the gather slow option, as it complicates the game for almost nothing.
