### ISSUE TITLE
The editor says 0xdead and 0xbeef are invalid operands

### ISSUE THREAD

**Issue by jrmithdobbs** [simon987/Much-Assembly-Required#100]
The code will still compile and run fine but the red xs do not go away in the editor.

Should be observable with this snippet:
![screen shot 2018-01-01 at 1 26 30 pm](https://user-images.githubusercontent.com/48147/34471196-b0627f5c-eef7-11e7-9f85-a7d75b911a1a.png)

```
  mov a, 4
  mov b, 0xdead
  mov c, 0xbeef
  hwi HOLO_HW ; change color
```

**Comment by simon987** [comment]
Moved to https://github.com/simon987/Much-Assembly-Required-Frontend/issues/15
