### ISSUE TITLE
Refactoring: Move buffers' implementations

### ISSUE THREAD

**Issue by arthurpaulino** [simon987/Much-Assembly-Required#111]
Every hardware might require its own way of buffering, thus implementing hardware-specific buffers ([[1](https://github.com/simon987/Much-Assembly-Required/blob/master/Plugin%20Cubot/src/main/java/net/simon987/cubotplugin/Cubot.java#L35)] and [[2](https://github.com/simon987/Much-Assembly-Required/blob/master/Plugin%20Cubot/src/main/java/net/simon987/cubotplugin/Cubot.java#L37)]) inside the [Cubot's class](https://github.com/simon987/Much-Assembly-Required/blob/master/Plugin%20Cubot/src/main/java/net/simon987/cubotplugin/Cubot.java) doesn't feel right.

My suggestion is to move them into their respective hardware classes.

**Comment by simon987** [comment]
The code that sends the information to the client only has direct access to the ControlledUnit interface, which has to implement a way to return a message buffer so it made sense to place it in the Cubot class. It's to avoid the overhead of checking if a Cubot's CPU exists, and that a ComPort hardware exists and is attached to that CPU every time the buffer has to be updated. Also, future hardware will re-use the same internal buffer (if applicable) so in a sense it's not really hardware specific (even if the name currently is).

**Comment by arthurpaulino** [comment]
>future hardware will re-use the same internal buffer (if applicable) so in a sense it's not really hardware specific (even if the name currently is).

that'd be awesome but won't they overlap?

**Comment by KevinRamharak** [comment]
Ah ok that makes sense. So it's just an internal buffer in the CPU that the hardware interfaces to? Then it's up to the programmer to make sure they use the buffer the correct way. That seems like a good challenge and realistic.

**Comment by arthurpaulino** [comment]
i understand now. i just don't know how to make it happen yet. maybe define a priority order among hardware parts to use the buffer?
anyways, closing the issue. i'll update the cubot's wiki diagram soon with the internal buffers module.
