### ISSUE TITLE
[BUG] Words in strings in DW commands that has the form \w+: are stripped 

### ISSUE THREAD

**Issue by Spinkelben** [simon987/Much-Assembly-Required#112]
Minimal code example that diplay the bug

```
HWID_HOLO EQU 0x9
HOLO_DISPLAY_STRING EQU 0x2

.data

str: DW "test___:"          ; A string with a word followed by a colon
DW "OVERFLOW!!!!"           ; Just a random string that follows in memory after the first stirng 'str'

.text

; Print message
mov X, str ; Set X to address of string
mov A, HOLO_DISPLAY_STRING
HWI HWID_HOLO

```

When this code is executed the robot prints "OWERFLOW" in the hologram projector, instead of "test___:" as would be expected. If the string has multiple words it is only the which end in ':' word that are stripped, e.g. "Hello test: sentence" becomes "Hello  sentence".

**Comment by DBJ314** [comment]
If I had to guess, I would say that it is treating `"test___:"` as a label somehow. On an unrelated note, the string should be written as `str: DW "test___:",0`. Strings don't automatically get null termination.

**Comment by simon987** [comment]
Problem is:
```Java
    private static String removeLabel(String line) {


        return line.replaceAll("\\b\\w*\\b:", "");


    }
```

Even removes labels inside the quotes. I don't have enough experience with Regex to change it so it ignoes labels in quotes. For now you can escape it `\:`. If nobody volunteers to help I'll figure out a few to do it without Regex but it probably won't be pretty.

**Comment by DBJ314** [comment]
[This](https://stackoverflow.com/questions/1191397/regex-to-match-values-not-surrounded-by-another-char) stackoverflow page looks like it could help

**Comment by Spinkelben** [comment]
I know that strings don't get null terminated automatically. But for the sake of example it left out the null terminator, as this causes the next string in memory to be written instead of just the empty string ;)

Also I suggest changing the pattern to `"^\\s*\\b\\w*\\b:"`. The `^` matches the start of a line, while `\\s*` matches any number of whitespace characters. The resulting pattern only matches labels if the first non-whitespace characters on a line is a word that ends in `:`, reading left to right.
