### ISSUE TITLE
Tile-selecting hardware

### ISSUE THREAD

**Issue by sg495** [simon987/Much-Assembly-Required#124]
It would be very handy (e.g. for navigation purposes) to have some hardware which allows the coordinates of a tile highlighted by the mouse pointer to be read by the cubot. For example, when the interrupt is triggered the coordinates of the currently highlighted tile (if any) could get read into the X and Y registers. 

This could be an extension of the LiDAR hardware (e.g. a `LIDAR_GET_TARGET_POS` action), or some entirely new hardware altogether (a light-weight LiDAR of sorts). Additional features could include reading info about objects on the highlighted tile into other registers and/or memory.

**Comment by DBJ314** [comment]
That would be cool, but it is not strictly necessary. In my bot, I can type 'g' followed by 2 hexadecimal characters to go to that location. I hold the mouse over the tile I want to go to, and type in the coordinates. If it says '15,9', I type 'gf9'

**Comment by simon987** [comment]
Not a priority but it could be added in the future.

**Comment by simon987** [comment]
Not a priority but it could be added in the future.

**Comment by mlaga97** [comment]
Perhaps call it mouse to match keyboard, and then it would make sense to get cursor position as well as left, middle, and right click events.

**Comment by simon987** [comment]
I was thinking that when you click on a tile it would select it, and that you could fetch the selected tile's coordinates. It would be hard to get mouse events working in real time

**Comment by DBJ314** [comment]
That would be interesting. I am imagining a tile-selected interupt.

**Comment by mlaga97** [comment]
My thoughts are that click events could be collected along with position data, and added to a queue in a similar way to the keyboard hardware, just with additional metadata. If the user just wants position, that could be collected separately once per tick and would function more like the LiDAR hardware.

**Comment by sg495** [comment]
> I was thinking that when you click on a tile it would select it, and that you could fetch the selected tile's coordinates. It would be hard to get mouse events working in real time

Yeah, that's exactly what I was trying to say originally (probably failing to do so)... 

>  click events could be collected along with position data, and added to a queue in a similar way to the keyboard hardware, just with additional metadata.

... but I have to admit this click-event queue idea opens up some rather neat possibilities. Only issue I see is possible conflict with future implementation of frontend features based on clicking, but I guess we'd cross that bridge if and when we came to it.

**Comment by simon987** [comment]
Not sure about an actual mouse hardware with events and such. I'd prefer to promote automation rather than mouse & keyboard controlled keyboard, but I wouldn't mind adding some kind of tile cursor thing, which could be useful for the Rocket structure ((#36) and the mortar hardware (#20) in the future.  
I'd like to keep the frontend as simple as possible
