### ISSUE TITLE
Realistic energy costs.

### ISSUE THREAD

**Issue by sg495** [simon987/Much-Assembly-Required#131]
This is the energy counterpart of issue #130: current energy costs and energy storage are rather unrealistic, so I propose to change them to more realistic values, tuned to x86-16 era hardware.

Different models of Intel 286 had power dissipations in the range of 1-2W, with performance in the range of 1-2MIPS, so I will assume a rough figure of 1W/MIPS. In issue #130 I proposed using a 1MIPS Intel 286-like processor for cubots, which would give an energy cost of 1μJ per instruction, or 1mJ per millisecond of execution time, or about 1,000,000 times smaller than the 1kJ currently specified in the [CPU wiki page](https://github.com/simon987/Much-Assembly-Required/wiki/CPU).

Power consumption for floppy disks is minimal when idle at 10-20mW (so we can probably disregard that), while power consumption at access time is much larger at 10-20W. Taking 20W consumption and a 20ms access time (suggested in issue #130), the cost of a single floppy read/write operation would be around 400mJ, which is about 2,500 times smaller than the 1kJ currently specified in the [Hardware: Floppy Drive wiki page](https://github.com/simon987/Much-Assembly-Required/wiki/Hardware:-Floppy-Drive).

The energy available to cubots depends on how big/heavy @simon987 imagined them to be. Batteries give 150-900kJ per kilo of battery material, depending on the type, and the ones available at the time of x86-16 tech would have probably been around the lower part of the spectrum: assuming a 300g battery with 200kJ/kg gives 60kJ, which is about 1,000 times less than the 60,000kJ currently specified in the [Hardware: Battery wiki page](https://github.com/simon987/Much-Assembly-Required/wiki/Hardware:-Battery). Even with modern day tech, a 60'000kJ battery would weigh around 60kg.

Assuming that cubots are large/heavy enough, a 6kJ battery would only require revising the units currently employed from kJ to J. Revised energy consumption for floppy access would then bring their effective cost down by 2.5x: they costed 1kJ in a 60'000kJ battery, now they would cost 0.4J in a 60'000J battery. Revised energy consumption for instructions brings their effective cost down by 1000x, which is more realistic: with the previous figure, a non-recharged cubot battery would only support 1 minute of computation, while now it would support a more reasonable-sounding 16 hours.

The energy costs of other hardware operations would also need to be revised: some of them depend on cubot size/weight, others just on the tech being used. Also, real-world autonomous robots often have non-negligible standby energy consumption, and a low-power sleeping mode kicks in when they need to recharge.

**Comment by simon987** [comment]
The energy costs were roughly based on my estimate of the execution costs for the server's Java code, and were never meant to be realistic. Players abusing infinite loops should not be able to so it for 16 hours in a row.

However, if you can come up with realistic energy costs that also push users to use the least server resources as possible I don't mind.

**Comment by sg495** [comment]
> Players abusing infinite loops should not be able to so it for 16 hours in a row.

Yeah, I have to agree with that...

> However, if you can come up with realistic energy costs that also push users to use the least server resources as possible I don't mind.

All right, I'll give it some thought 😄
