### ISSUE TITLE
Container / chest

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#138]
Implement a simple GameObject that can hold a configurable amount of items. Items can be stored and retrieved with the laser hardware. Should implement `InventoryHolder` interface

**Comment by J-Eisen** [comment]
Hey @simon987! I'd love to take a crack at this.

**Comment by simon987** [comment]
I think that @asabedia is already working on it: https://github.com/asabedia/Much-Assembly-Required/tree/feature/138

You might want to continue where he left off or wait until he manifest himself since nobody assigned officially himself to the issue

As I said in another issue you can contact me on the Slack channel for information and you can use the `spark` branch for now if you want to avoid the hassle of setting up the frontend for local development. (I'm currently in the process of refactoring the server so it no longer depend on MySQL and PHP)

I might not respond very fast since I'm in the middle of final exams.

Thank you!

**Comment by J-Eisen** [comment]
All good. Thanks for the heads up. :) I’ll set up the slack. Good luck with your exams!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by asabedia** [comment]
Sorry @simon987, I am very new to open source projects, I am currently working on this feature. Do i need to ask to be assigned to a feature prior to starting? Just so I can follow proper convention for future issues.

**Comment by simon987** [comment]
Hi @asabedia, there isn't really a convention but in the future you can comment the issue to let people know you are working on it
