### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#152]
Installation instructions in the wiki should be updated for Windows, Mac, Linux (ideally Debian and Arch) and Mac instructions should be added to README.md

**Comment by Anarcroth** [comment]
Hi!
I've tested this on Arch Linux and can add installation instructions to the README for it.
(I didn't find the installation instructions in the wiki anywhere...I might be blind tho)

**Comment by simon987** [comment]
Hello @Anarcroth,
feel free to update the README.md file in a PR with the Arch Linux instructions. 
The wiki couldn't load for me on mobile but as far I remember there should be a page for arch installation.

Thank you! :)

**Comment by Anarcroth** [comment]
@simon987 Yes, found it! :)
Thank you. I will get on it and you can share if the formatting fits the documentation style.

**Comment by simon987** [comment]
@Anarcroth Looking good, thank you!

Leaving the issue open for MacOS instructions

**Comment by senatormailman** [comment]
Hi, I am running macOS Sierra, and I am trying to install at the moment. If I am successful, I will update the Readme with the information I get!

**Comment by senatormailman** [comment]
I was able to run the server easy. I set up a readme section for macOS.
