### ISSUE TITLE
Stack representation image in wiki

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#157]
An image should be created to help understand the stack

See: [The stack, procedures and the stack frame](https://github.com/simon987/Much-Assembly-Required/wiki/Basic-Assembly-tutorial#the-stack-procedures-and-the-stack-frame)

**Comment by yatesal** [comment]
Hi, I've included an image to help visually represent the stack: https://github.com/simon987/Much-Assembly-Required/wiki/Basic-Assembly-tutorial#the-stack-procedures-and-the-stack-frame

**Comment by yatesal** [comment]
Would either of these diagrams suffice?

![stack2](https://user-images.githubusercontent.com/25143248/40337146-b1964432-5d22-11e8-9997-a5e5a48d06bd.png)

![stack](https://user-images.githubusercontent.com/25143248/40337014-ea5c5564-5d21-11e8-9f86-5a5979ce5005.png)

**Comment by simon987** [comment]
The second picture looks great but the stack pointer arrows are confusing IMO, in the first step, `SP` should point to Item 4 (or 5, since `SP` is decremented before the item is copied to the stack, you could make the arrow point to the blank space after item 4 to illustrate that), in the middle step `SP` should point to Item 5, and in the rightmost step, `SP` should point to item 4.    
I think that placing the arrows in the middle of the blocks would make it less confusing

Sorry if I'm picky! Thanks again

**Comment by yatesal** [comment]
I don't think you're being picky at all! Here's an updated version.

![stack3](https://user-images.githubusercontent.com/25143248/40339650-38288bb0-5d30-11e8-826f-d0b924b01192.png)

**Comment by simon987** [comment]
Awesome ! You can update the link in the wiki, I'll close the issue
