### ISSUE TITLE
Game objectId de-associating ?

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#162]
I imagine that could be due to `getNextObjectId()` not being thread safe? Maybe it would be wiser to rely on mongodb ids.

Stack strace:    
```
Exception in thread "Thread-10" java.lang.ClassCastException: net.simon987.npcplugin.ElectricBox cannot be cast to net.simon987.npcplugin.NonPlayerCharacter
	at net.simon987.npcplugin.Factory.update(Factory.java:78)
	at net.simon987.server.game.world.World.update(World.java:183)
	at net.simon987.server.GameServer.tick(GameServer.java:192)
	at net.simon987.server.GameServer.run(GameServer.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by simon987** [comment]
Okay I think I figured it out:
The current `nextObjectId` is `10`, and it is saved in the database as `7` from the last save    
The server restarts without saving    
It restores `7` from the database, the next 3 objects overwrites existing objects.

I think the only option is to use mongodb's ObjectId()

**Comment by mike2ykme** [comment]
I’m going to suggest something but I’m not entirely sure what you’re looking at because I just started looking at your project. However What about using an atomic Integer and just getting the next int or something similar?

**Comment by simon987** [comment]
Are you referring to [AtomicInteger](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/atomic/AtomicInteger.html) ?
I'm not convinced that it's a thread safety issue anymore (see last comment), but changing to AtomicNumber would certainly be a good idea, just to be sure thanks !

**Comment by simon987** [comment]
I think that I'll switch to [ObjectId](https://docs.mongodb.com/manual/reference/bson-types/#objectid)

**Comment by simon987** [comment]
Couldn't reproduce the problem at all after switching to BSON ObjectId
