### ISSUE TITLE
Error parsing strings in assembler

### ISSUE THREAD

**Issue by KevinRamharak** [simon987/Much-Assembly-Required#163]
when trying to use a string like:
```s
string: DW "Hello from \x1B[1"
```
The server will fail assembling and log:
```
[06/06 07:52:26:811] [SEVERE] Invalid operand ""Hello from \x1B[1"@3
```

Not yet sure what the problem is

**Comment by Francessco121** [comment]
Works fine as of the latest version, although I don't think it escapes that how you might think, it parses into `Hello from x1B[1`. Looking at the error message, it looks like you accidentally started it with two double quotes (suppose I'm a bit late to solving this however 😄).
