### ISSUE TITLE
Support for character literals

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required#164]
Support for character literals would be nice.
The assembler uses UTF-16 BigEndian encoded strings right now. This makes sense for a 16-bit byte. The question is which and how the escape sequences are handled right now.  The assembler uses [`StringEscapeUtils.unescapeJava()`](https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/StringEscapeUtils.html#unescapeJava(java.lang.String)) right now. [Maybe switch to a handwritten string parser](https://stackoverflow.com/questions/3537706/how-to-unescape-a-java-string-literal-in-java)?

**Comment by simon987** [comment]
Looks like most common escape sequences are handled uncluding unicode and `\0` etc.
You can reopen this if you had other escape sequences in mind

**Comment by kevinramharak** [comment]
Uncluding or including? I'll do some tests on the ones people might actually use and if something comes up ill reopen

**Comment by simon987** [comment]
*including
