### ISSUE TITLE
Using an invalid Unicode escape sequence crashes the assembler

### ISSUE THREAD

**Issue by Francessco121** [simon987/Much-Assembly-Required#169]
Since strings are parsed using `StringEscapeUtils.unescapeJava` ([source line](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/assembly/Assembler.java#L159)), they inherit all of Java's escape sequences including Unicode characters in the form of `\uXXXX`. However, if the user does not use exactly 4 hexadecimal digits after `\u`, this method throws an `IllegalArgumentException` which closes the WebSocket without a front-end error since it's not being caught.

I have a quick fix over at [https://github.com/Francessco121/Much-Assembly-Required/tree/bug/unicode-string-crash](https://github.com/Francessco121/Much-Assembly-Required/tree/bug/unicode-string-crash) if you'd like me to submit a pull request, I haven't submitted one yet since this is a pretty trivial fix and the front-end editor currently does not validate this.

**Comment by simon987** [comment]
Thank you for the info.
If you could submit the PR, that would be great.

I'll try to modify the front-end editor so it has the same behavior when I have time
