### ISSUE TITLE
Factories and iron share the same map info bit field

### ISSUE THREAD

**Issue by Francessco121** [simon987/Much-Assembly-Required#170]
Both [factories](https://github.com/simon987/Much-Assembly-Required/blob/master/Plugin%20NPC/src/main/java/net/simon987/npcplugin/Factory.java#L18) and [iron](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/game/world/World.java#L29) are defined with the tile info `0x0200`, making it impossible to tell them apart. This appears to be a mistake in the `Factory` class as [factories were always documented as using the bit field `0x2000`](https://github.com/simon987/Much-Assembly-Required/wiki/Hardware:-LiDAR#tile-content-bit-fields).

This is something to keep in mind if #155 is addressed first.

**Comment by simon987** [comment]
Oh, thanks for the info, I'll keep that in mind for when I sort out the map_info values problem.
(I don't currently have the time and I doubt I will be able to find the time in the near future but I'll try)
