### ISSUE TITLE
Assembler outputs incorrect binary when subtracting a register by a label in a memory displacement operand

### ISSUE THREAD

**Issue by Francessco121** [simon987/Much-Assembly-Required#172]
When using a memory displacement, the operator is not taken into account when the displacement value is a label.

For example:
```asm
label:
  mov X, [X + label]
  mov Y, [Y - label]
```
The encoded value to be added to the registers will be the same for both `mov` instructions, instead of the second one being negated.

Disassembling the previous example results in the following (note, the actual address isn't really relevant):
```asm
mov X, [X + 0x000d]  ; A9 41 00 0D
mov Y, [Y + 0x000d]  ; B1 81 00 0D
```

The issue seems to be that [this code block](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/assembly/Operand.java#L215) only gets the address of the label and doesn't check the operator. With an integer literal, handling of the operator is offloaded to `Integer.decode`.

**Comment by simon987** [comment]
You're right, it doesn't check the sign for labels.
This is quite an easy fix, one would only have to check the sign (first character of the string) and apply it to `data`

**Comment by bobbyjudd** [comment]
Is this issue still up for grabs?

**Comment by simon987** [comment]
@bobbyjudd Yes. Let me know if you need assistance with the issue / project setup (Ideally in the slack channel, see README.md for the link)

Thank you!
