### ISSUE TITLE
User stats

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#182]
User stats should be added and displayed on the leaderboard (See: [UserStats](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/user/UserStats.java)):

- [ ] Death counts
- [ ] Total execution time (ms)
- [ ] Walk distance (tiles)

**Comment by woosle1234** [comment]
Hi, I would like to try and implement this feature. Can you just briefly explain how the userstats display, set, and get data? Also is the execution time a real-time timer or in-game timer?

**Comment by simon987** [comment]
Stats are displayed in the 'leaderboard page':
- [Controller](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/web/LeaderBoardPage.java)
- [View](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/resources/templates/leaderboard.vm)

Total execution is real-time - the execution time is already calculated (it is used to calculate the energy cost of CPU execution)

You can set user stats by directly manipulating their UserStats attribute (you can find an exemple [Here](https://github.com/simon987/Much-Assembly-Required/blob/master/Plugin%20NPC/src/main/java/net/simon987/npcplugin/event/VaultCompleteListener.java))

Implementation details:
I'd like that *Event & *Listener classes be created for each stat, so that the stats are set inside the listener, you can find an exemple of events being dispatched [Here](https://github.com/simon987/Much-Assembly-Required/blob/c50cc8c364195249238f6da5024a94e3da0c678d/Server/src/main/java/net/simon987/server/game/world/World.java#L145-L147)

If you need any more info let me know, thanks!

**Comment by pommilp** [comment]
shouldn't this be closed?
