### ISSUE TITLE
Can't create account or login

### ISSUE THREAD

**Issue by OrdoFlammae** [simon987/Much-Assembly-Required#193]
I can't create an account on the game website. Every time I try, it responds with 500 Internal Server Error. I tried logging in with the same account, to see if it's just that the account already exists, and I also get a 500 Internal Server Error.

**Comment by OrdoFlammae** [comment]
Oh, the account I'm trying to create has username OrdoFlammae.

**Comment by simon987** [comment]
@OrdoFlammae Hi, thank you for the heads up.
The server this is hosted on ran out of disk space, causing the mongodb service to crash.
This should be resolved now, sorry about that

**Comment by 34673** [comment]
Hello. Did you purge the user list to fix this? It looks like my account doesn't exist anymore. Or maybe is it another crash?

**Comment by simon987** [comment]
> Hello. Did you purge the user list to fix this? It looks like my account doesn't exist anymore. Or maybe is it another crash?

Yes, I regularly reset the server for various reasons, I can try to recover your information if you wish (no guarantees), just let me know your username.

**Comment by 34673** [comment]
@simon987 Sorry for the delay. It's "Eagle_Beep". I'll make sure to backup data in the future, now that I'm aware of this detail. Thanks for helping with this!

**Comment by simon987** [comment]
@34673 
Hi, sorry I thought that I had a backup of the database, but I didn't. However I could recover from the logs the last recorded time code was uploaded from this account: [pastebin](https://pastebin.com/jDTQ5pPQ). 

The hex dump could technically be disassembled but I don't have an up to date disassembler (I'm sure someone on the Slack channel could help you with that).

Sorry!

**Comment by 34673** [comment]
Hmm... I'm not sure if that will help much. The script I had was fairly basic, but the thing I mainly wanted back was a wall of EQUs that basically reflected the entire API in a more verbose fashion. This was probably lost during compilation. I just wanted to avoid going through the whole wiki again to build it up. 😛 
Thanks for checking though; much appreciated. I'll be more careful next time!

**Comment by kevinramharak** [comment]
@34673 For a dissasembler look at https://github.com/Francessco121/mar-toolkit/tree/master/src/mar_disassembler.

For constants a small list can be found here: https://github.com/simon987/Much-Assembly-Required/wiki/Snippet:-Constants and here https://github.com/mlaga97/MuchAssemblyRequiredBot/blob/master/constants.s

**Comment by 34673** [comment]
@kevinramharak That's very similar to what I had, indeed! However, I think I will remake it myself in the next update for the sake of having everything in check; both aesthetically and content-wise. Last time, we were discovering this with a friend, and despite hints of deeper gameplay/goals, we couldn't find much to do except wandering around, mining and _trying_ to use any of the 'official' communication devices in game. So we're unlikely to play much until there is an update that extends on the gameplay. 😛 
It was a pretty fun experience however! I'm definitely keeping an eye around.

**Comment by DBJ314** [comment]
Hacked NPCs could be very fun once someone figures out how to do interesting things with them.
I would totally use them if someone else wrote code for them. :)
Seems nobody has done that yet.
