### ISSUE TITLE
Wiki local clone has invalid characters in the file names (for Windows)

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required#216]
Some files have a `:` in the file name which is an illegal character for file names on Windows. I suggest changing these to `-`.

**Comment by simon987** [comment]
I removed the `:` characters in the page names (hopefully it didn't break too many links), let me know if that fixed that issue on Windows

**Comment by kevinramharak** [comment]
This fixes the issue. I did a quick regex search and it seems some references auto fixed themselfs unless you changed a few as well. I fixed the broken links with this commit [b3e6263](https://github.com/simon987/Much-Assembly-Required/wiki/_history).

**Comment by simon987** [comment]
great, thank you!
