### ISSUE TITLE
non-collaborators can not push to Wiki repository

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required#217]
It seems I do not have permission to push to the wiki repository. Working in the web editor becomes quite tedious when working on some of the more technical documents like the instruction set. Is there any way to set the permissions of the wiki? Anyone can edit the wiki online without any authorization so I assume a similar permission on the wiki repository would not be against the current flow of the wiki.

**Comment by simon987** [comment]
All I have on my end is this:
![image](https://user-images.githubusercontent.com/7120851/68086479-97bf1d00-fe1a-11e9-8f4f-e44282025f3d.png)
I'll try to look if I can figure out something
In the meantime I added you as a collaborator so you should be able to push to the wiki

**Comment by kevinramharak** [comment]
Thank you. It seems this is intended behaviour. Probably has to do with the wiki repo being a subrepo of the project. I will post here when I am done with my changes.
> https://github.community/t5/How-to-use-Git-and-GitHub/Allow-push-to-wiki-for-other-users/m-p/32783/highlight/true#M8828
