### ISSUE TITLE
Harvester bots can walk over Cubot (and vice-versa

### ISSUE THREAD

**Issue by OrdoFlammae** [simon987/Much-Assembly-Required#222]
When walking around, the harvester bots can walk over the cubots, and vice-versa. I need to test this for cubots walking over cubots, to see if the same thing happens. This seems like a bug, and is kind of annoying when trying to turn towards a bot, and running through them.

**Comment by simon987** [comment]
This is indented behavior, this is to prevent players from being blocked & being unable to play if they spawn at the wrong place
