### ISSUE TITLE
Assembler directives documentation/implementation

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#228]
[Wiki page](https://github.com/simon987/Much-Assembly-Required/wiki/Assembler-directives)

- [x] Document `ORG` directive
- [x] Create unit test for documented ORG example
- [x] Document string constants in `DW`
- [x] Create unit test for documented string example
- [x] ~Implement character literals (#164)~
- [x] ~Document character literals in `DW`~
- [x] ~Create unit test for documented character example~
- [x] Implement octal literal (or confirm that it works both in the editor & assembler) (#166, #50)
- [x] Create unit test for documented octal example
- [x] Create unit test for documented binary example
- [x] Document `.text` and `.data` sections (verify that this information is not found elsewhere in the wiki, if so, link it)

**Comment by kevinramharak** [comment]
Did you decide to not implement character literals? having strings is good enoungh imo.
