### ISSUE TITLE
Console message buffer max size is broken

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required#234]
The wiki states that the internal hardware console buffer can contain up to 40 words but the current implementation actually allows for up to 40 messages instead of 40 words `ArrayList<char[]>(40)`. Each message has a max of 8 words and in the source its always 8 words at the time. The git history shows that it has always been like this, but I always implemented it to work with 40 words max so im not sure.

**Comment by simon987** [comment]
IIRC it was always meant to be 40 messages total, the documentation should be changed

**Comment by kevinramharak** [comment]
I'll fix the docs then
