### ISSUE TITLE
Inc/Dec Instructions

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#26]
Implement Inc (increment) and Dec (decrement) instructions.

**Comment by cooprocks123e** [comment]
Hey, I'm working on this, and I was wondering: what's the procedure for assigning new opcode numbers?

**Comment by simon987** [comment]
You should use the next available one (The Instruction Set Wiki page might not be 100% up to date) which is 41

**Comment by cooprocks123e** [comment]
Thank you. INC is 41, DEC is 42.

**Comment by ChartreuseK** [comment]
Due to SAR taking 41 (0x29). INC should now be 42 (0x2A), and DEC 43 (0x2B) as they are in my pull request. Sorry for taking over if you were still working on this, no updates had come out in 10 days.

**Comment by cooprocks123e** [comment]
Haha yeah sorry, I never got a local build set up and I went away for a
couple of days. Feel free to take over :)
