### ISSUE TITLE
Harvester NPC should spawn a Biomass blob on death

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#33]
When destroyed or when it reaches maximum age, harvester NPCs should spawn a biomass blob. The amount of biomass units in the blob should be larger than a regular biomass blob.

**Comment by jtara1** [comment]
I'll work on this tonight when I'm on desktop and can see class outline more easily. Your code could use more documentation. Which IDE you're using? Some developer setup tips would be nice.

Does the GameObject abstract class that represents any object that can be placed on a TileMap  object?

I created a BiomassBlob that'll spawn through the method HarvesterNPC.isDead(Boolean) but what do I need to do to tell the server to add the Biomass to the GameServer?

**Comment by simon987** [comment]
I'm using IntelliJ Idea. The maven setup has been implemented only a few hours ago so I didn't have time to write a small guide.
