### ISSUE TITLE
Laser hardware Should damage NPCs

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#34]
Players should be able to damage Harvester NPCs using the laser hardware. I don't know if I want to enable PvP, maybe it could be enabled only in certain areas (like the wilderness in runescape). 
Harvester NPCs should implement the Damageable interface, and have a damage(int hp) function which would setDead(true) when hp <= 0

**Comment by mlaga97** [comment]
I've started working on this. Any preference for default health, damage, and regen rate?

**Comment by simon987** [comment]
Ideally it would be loaded from the config.properties file. For now you can leave the PvP part off. I'm not sure if I want to have PvP and I don't know yet how I want the re-spawning to work

**Comment by mlaga97** [comment]
Does 100HP, damage of 20, and regen of 5 work (held in the config file, of course)? That would be 5 hits in a row to kill, which seems reasonable.

PvP should probably be configurable and also another issue.
