### ISSUE TITLE
Game display component size

### ISSUE THREAD

**Issue by arthurpaulino** [simon987/Much-Assembly-Required#40]
The game display component is not being resized to make the site fit in the screen comfortably.
![resize](https://user-images.githubusercontent.com/1919110/34392684-76022fa2-eb2c-11e7-8280-4d952301ff61.png)

**Comment by simon987** [comment]
Looks like it's a few pixels too large to fit in the container. What browser / device are you using ? And are you resizing the Window at all after the game is loaded?

**Comment by simon987** [comment]
Moved to appropriate repo: https://github.com/simon987/Much-Assembly-Required-Frontend/issues/1
