### ISSUE TITLE
feature: face expression as hardware

### ISSUE THREAD

**Issue by fredlllll** [simon987/Much-Assembly-Required#46]
a new hardware that can change the face of the bot to something approriate (can also be used for debugging kinda). maybe even allow custom faces made by the user, either using bitmaps in memory/.data or profile images of the web interface

**Comment by simon987** [comment]
I don't have enough Javascript/Phaser knowledge to do something like that. I would have to draw a bitmap, and skew it so it would line up with the face of every Cubot.

**Comment by fredlllll** [comment]
is the robot prerendered then?

**Comment by simon987** [comment]
https://muchassemblyrequired.com/mar/sprites.png Yeah
