### ISSUE TITLE
Support binary and octal notations

### ISSUE THREAD

**Issue by mgiuffrida** [simon987/Much-Assembly-Required#50]
It'd be helpful to support binary (`0bXX`) and octal (`0oXX` or `0XX`) notations, since these are common practice in many programming languages.

If not, the editor should show an error when binary notation is used (octal is harder), and the wiki should explain that these notations are unsupported.

**Comment by simon987** [comment]
Problem is that for the JavaScript editor, `0b1` is valid:
```Javascript
//Check IMM
if (!isNaN(Number(text)) && Number(text) === Math.floor(Number(text))) { //Returns true
    return OPERAND_IMM;
}
```

But it is invalid for the Java parser:
```Java
    private boolean parseImmediate(String text) {

        text = text.trim();

        try {
            type = OperandType.IMMEDIATE16;
            data = Integer.decode(text); //Throws NumberFormatException
            value = IMMEDIATE_VALUE;
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
```

So I'll look into a way to parse binary numbers in Java. It might become confusing because in FASM and some other languages/assemblers, `0001b` is how you would write a binary number

**Comment by simon987** [comment]
When you try to write `0oXXX` or `0eXXX` with the editor, an error will show up now.
