### ISSUE TITLE
Hologram Projector hardware should be able to display the value 0x0000

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#53]
One idea would be to display the contents of B if A is non-zero.

**Comment by renpnal** [comment]
I suggest displaying contents of B if A is 1 and clearing the display if A is 2. This is because inventory for example polls if A is 1 and clears if A is 2.

**Comment by sf17k** [comment]
Suggestion: Either mimic other hardware and have actions like CLEAR = 1, DISPLAY = 2, or simply remove the ability to clear.
