### ISSUE TITLE
MOV [mem] [mem] does not work as expected

### ISSUE THREAD

**Issue by KevinRamharak** [simon987/Much-Assembly-Required#58]
So this piece of code does not work as expected:
```s
main:
    MOV [display_mode], TEXT
    MOV A, text
    MOV [temp], KEY_D
    MOV [A], [temp]        ; this does not work
    MOV [A], KEY_D
    CALL display
    brk
```

The docs at [ousob](http://www.ousob.com/ng/iapx86/ng1676e.php) state this note:
>               MOV cannot move from memory to memory or from
>               a segment register to a segment register.

Yet the comments in the [`MovInstruction.java`](https://github.com/simon987/Much-Assembly-Required/blob/master/Server/src/main/java/net/simon987/server/assembly/instruction/MovInstruction.java) state:
```
/**
 * The MOV instruction copies data from a source to a destination.
 * it overwrites the value in the destination. The destination can be
 * memory or register, while the source can be an immediate value, memory
 * or register.
 */
```
I tried to follow the source code line by line, but without a debugger or log files its hard to see what exactly happens

**Comment by mgiuffrida** [comment]
Oh, so this wasn't intentional? It seems like in most instruction sets (like x86) `mov` cannot copy from mem to mem, as a design decision.

Not that there's any reason you have to simulate this, just wondering.

**Comment by KevinRamharak** [comment]
Nope check the file diff. Just a simple bug. Should work as documented in
the Instruction set docs and source code commets

**Comment by simon987** [comment]
8086 had a more compact (but more complex) way to encode instructions but since memory is only word-addressable and we have 128Kb of memory, it makes more sense to allow it
