### ISSUE TITLE
Feature: Hardware bot color

### ISSUE THREAD

**Issue by Wofi** [simon987/Much-Assembly-Required#63]
Have a hardware that controls what color the bot is-
poll (1) could push the R, G, B onto the stack
2 thru 4 could set the R, G, B of the color
perhaps you could set a custom low-battery color with 5 thru 7, so red bots can still show low battery

I think this should be possible? the sprite sheet you linked in #46 only had green, which makes me think the default sprites are recolored for low battery

**Comment by simon987** [comment]
I think that a simpler way to do it would be to set the color with the Hologram Hardware, it'll avoid having to program another hardware.   
Something like:
```assembly
MOV A, 3 ; DISPLAY_COLOR
MOV B, 0x00FF ; Specify color 0xFF0000 (red) in B:C registers, first byte is ignored
MOV C, 0x0000
HWI 9
```
This color would always have priority over the low battery color, which would avoid dealing with the custom low battery color deal. 

It would be a simple modification both server-side and client-side (not sure about the performance though..)
