### ISSUE TITLE
Documentation for Hologram Projector

### ISSUE THREAD

**Issue by calvinburkhead** [simon987/Much-Assembly-Required#71]
Example for color uses wrong registers.

> Changes the color of the cubot using the value of the B:C register (e.g. A: 0x00AA and B: 0xBBCC, would be RGB 0xAABBCC)

Should be

Changes the color of the cubot using the value of the B:C register (e.g. **B**: 0x00AA and **C**: 0xBBCC, would be RGB 0xAABBCC)

**Comment by arthurpaulino** [comment]
the documentation is ok now, playing with colors didn't work out for me.

**Comment by simon987** [comment]
See #88
