### ISSUE TITLE
PUSHF & POPF Instructions

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#73]
Implement PUSHF & POPF instructions (push and pop flags)
opcodes 43 and 44 should be used

**Comment by Francessco121** [comment]
Hey, I'm currently trying to implement these but I have a couple quick questions.

Would there be any point to pushing the break and error flags? I would think no for the break flag, but definitely not sure about the error flag.

Also, is there any preference as to the bit order of the pushed flags?

**Comment by simon987** [comment]
I don't mind about the order, break flag should not be saved. Idealy, take a look at the Interrupt PR and use the same order (or the same function)
