### ISSUE TITLE
"Password must be 8-32 characters" is wrong and bad

### ISSUE THREAD

**Issue by anowlcalledjosh** [simon987/Much-Assembly-Required#79]
Last time I checked,

```
R'Lp5$v?kVN}q+KHMCo`Z92F]m;pX(
```

was only 30 characters long, and yet I get a message saying

```
Password must be 8-32 characters
```

when I try to sign up at muchassemblyrequired.com using it!

Why is there even a length restriction at all? Per NIST guidelines, the maximum should be large enough that no nonmalicious user would ever reach it:

> Users should be encouraged to make their passwords as lengthy as they want, within reason. Since the size of a hashed password is independent of its length, there is no reason not to permit the use of lengthy passwords (or pass phrases) if the user wishes.

(https://pages.nist.gov/800-63-3/sp800-63b/appA_memorized.html)

**Comment by simon987** [comment]
Should be on https://github.com/simon987/Much-Assembly-Required-Frontend
I'm using php `strlen($password)` to check the length, I think that some unicode characters in your string takes more than 1 byte. I changed the max password length to 96, should be more than enough.
