### ISSUE TITLE
Feature: Compass Rose or Cardinal Direction Markers on World View

### ISSUE THREAD

**Issue by ChartreuseK** [simon987/Much-Assembly-Required#86]
I feel it would help players while writing movement code to be able to visually see on the world view the orientation of cardinal directions. The top right edge being North is not necessarily intuitive. (My initial view was that the top left edge was North). 

Perhaps either some kind of Compass rose could be added to the World view to show the orientation. Alternatively the names or abbreviations of the direction could be overlaid on the arrows linking adjacent map tiles.

**Comment by dangranos** [comment]
There are very unnoticeable gray arrows at the edge of the world that I found only yesterday (There's a bit of problem with lack of contrast for buttons and UI elements...). Perhaps they could have letters like NESW on them?

**Comment by ChartreuseK** [comment]
Moved/Copied issue to the seperate front-end repo where it belongs.
See: https://github.com/simon987/Much-Assembly-Required-Frontend/issues/6
