### ISSUE TITLE
Hologram color bug

### ISSUE THREAD

**Issue by arthurpaulino** [simon987/Much-Assembly-Required#88]
The projections are displayed in proper colors iff the value of `B` is greater than `0x000F`.

For instance, if I want to display something in blue, 
```assembly
MOV B, 0x0000
MOV C, 0X00FF
```
doesn't work, but
```assembly
MOV B, 0x0010
MOV C, 0X00FF
```
does.

**Comment by KevinRamharak** [comment]
Seems to be sending the correct value from server to client:
```
MOV B, 0x0000
MOV C, 0X00FF
```
object send from server to client trough socket:
```
holoC == color
{parent: "kevinr", ..., holoC: 255, ...}
```

```
MOV B, 0x0010
MOV C, 0X00FF
```
```
{parent: "kevinr", ..., holoC: 1048831, ... }
// 1048831 == 1000ff
```

so it seems like client side is handling it wrong. Checking code and if i find it ill reopen the issue there

**Comment by KevinRamharak** [comment]
https://github.com/simon987/Much-Assembly-Required-Frontend/pull/11
should fix this issue

**Comment by arthurpaulino** [comment]
so... actually a frontend issue.
i suspected it'd be a frontend issue because the [server side](https://github.com/simon987/Much-Assembly-Required/blob/master/Plugin%20Cubot/src/main/java/net/simon987/cubotplugin/CubotHologram.java#L68) looks clean imo.
