### ISSUE TITLE
DOCKER and docker-compose.yml do not work

### ISSUE THREAD

**Issue by KevinRamharak** [simon987/Much-Assembly-Required#89]
- https://github.com/simon987/Much-Assembly-Required/blob/7821d428e226e584402df5ef707e71bf6e3ceb35/Dockerfile
- https://github.com/simon987/Much-Assembly-Required/blob/99cefba24517c7c1911702fed2cb025e124d71d4/docker-compose.yml

Because there is a seperate repo for the frontend the `docker-compose up` will not work.
There is an `database.sql` file in the frontend repo that has to be run on startup of the mysql database.

possible fixes:
- copy the `database.sql` file to here (bad idea imo)
- put both repos in one (bad idea imo)
- make the frontend a sub-repo of the server repo
- make the docker file get the `database.sql` file trough some `cdn.rawgit` magic or something like that

I am really inexperienced with docker so i cannot contribute much to a fix

**Comment by mlaga97** [comment]
It's not Docker, but I do have a _working_ Vagrantfile [here](https://github.com/mlaga97/Much-Assembly-Required-Vagrant). I would be fine with transferring ownership of the repository to Simon if that would simplify things from a documentation standpoint.

**Comment by simon987** [comment]
Should be fixed in 1a5d12a19fb7202ac366e97fa922cdf230ec0524
