### ISSUE TITLE
Guarantee Register Contents After BRK

### ISSUE THREAD

**Issue by ChartreuseK** [simon987/Much-Assembly-Required#90]
The register contents following BRK  seem to be undefined behaviour at this point. With the only changes being setting SP to 0xFFFF, BP to 0xFFFF, and IP to .text. I'd like to propose for convenience of sleep type routines and restoring a state machine that register contents be defined as being preserved over a BRK.

I'd also like to propose that BP be preserved and not set to a value, since it doesn't serve an intrinsic purpose (just an idiomatic one) and can be used as a general purpose register since there's no special instructions that use it (Just like on x86-16). It makes sense for the user to set it up when they need it.

Doing so would allow simpler sleep routines like below, where pushing all the registers is not required.
```
resume_vect: DW 0
resume_sp: DW 0
.text
    test [resume_vect], [resume_vect]
    jz   start
    mov SP, [resume_sp]
    push [resume_vect]
    mov [resume_vect], 0
    ret
sleep:
    pop [resume_vect]
    mov [resume_sp], SP
    brk
start:
```

(I'd also be a fan of SP not being reset and needing to be explicitly initialized as is behaviour on x86)

**Comment by simon987** [comment]
Initially, my main concern was not being able to resume from a server restart with all the registers intact, but it is no longer a problem. This was also added with convenience in mind: it would prevent players that have one or more PUSH instructions without a matching POP to get their code eventually overwritten by the stack. But I think that right now it would make more sense to remove it considering your use case.

**Comment by KevinRamharak** [comment]
So we can document it as intended behavior to preserve the registers in between ticks?
At least the `A`, `B`, `C`, `D`, `X` and `Y` registers.
`BP` and `SP` can be decided later.

**Comment by simon987** [comment]
Yes.

**Comment by ChartreuseK** [comment]
Even with keeping the use case of allowing players with stack errors to get a clean start with regards to `SP`, is there a need to reset `BP` as well? Stack operations aren't dependent on on its value, except when the user explicitly sets it up.

**Comment by simon987** [comment]
No I can't really think of a use case where resetting BP is necessary
