### ISSUE TITLE
Consuming Biomass should recharge the battery

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required#94]
As stated in #2, biomass should be consumed to generate energy. Clearing the inventory with INV_CLEAR should instantly remove the biomass unit from the inventory and recharge the battery about 4000Kj. Excluding the solar panel recharging, it would force the player to consume a biomass blob every 78 tiles of walking, which sounds reasonable (Calculating 100Kj for consuming the biomass, and 2 units per blob).

**Comment by djsheehy** [comment]
#95
